FROM node:lts-alpine as build-stage

ENV NODE_OPTIONS=”–max_old_space_size=4096″

WORKDIR /app
COPY package*.json ./
RUN npm install -g npm
RUN npm install
COPY . .
RUN npm run build:prod

FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY heroku_default.conf.template /etc/nginx/conf.d/default.conf.template

CMD /bin/sh -c "envsubst '\$PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf" && nginx -g 'daemon off;'
