FROM node:lts-alpine as build-stage

ARG BUILD_MODE

WORKDIR /app
COPY package*.json ./
RUN npm install -g npm
RUN npm install
COPY . .
RUN npm run build:prod

FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY azure_default.conf.template /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
